server:
  port: 8081
spring:
  application:
    name: wafer_order #设置当前应用名称，在eureka中Aoolication显示，通过该名称可以获取路径
  datasource:
    url: jdbc:mysql://localhost:3306/cloud2024?useUnicode=true&characterEncoding=utf8
    username: root
    password: 174713
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848 # nacos服务地址
