server:
  port: 8082
spring:
  main:
    web-application-type: reactive
  application:
    name: wafer-gateway #设置当前应用名称，在eureka中Aoolication显示，通过该名称可以获取路径
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos地址
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: order_route
          uri: lb://wafer-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: auth_route
          uri: lb://wafer-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}



